### ISSUE TITLE
Refactor to use repository model

### ISSUE THREAD

**Issue by aergonaut** [aergonaut/cody#225]
## TODO

- [x] ~~#227~~
- [x] Refactor mediators to create association to correct `Repository` instead of setting the `repository` attribute
  - [x] receive_pull_request_event.rb
  - [x] receive_issue_comment_event.rb
  - [x] apply_review_rules.rb
  - [x] create_or_update_pull_request.rb
- [x] Refactor `PullRequest` to use `Repository` model
- [x] Change GraphQL resolver to use `Repository` model
