### ISSUE TITLE
Use the new GitHub Apps API

### ISSUE THREAD

**Issue by aergonaut** [aergonaut/cody#63]
GitHub released the [GitHub Apps API](https://developer.github.com/apps/) and we should use it.

Benefits:
* Automatic bot user (e.g. codybot or similar)
* Easier webhook management for repo admins

## TODO

- [x] Use installation access tokens to authenticate ([Octokit docs](https://github.com/octokit/octokit.rb/blob/master/lib/octokit/client/apps.rb#L50))
- [x] ~~Track installations and associated repositories from webhooks~~
- [x] Use the GitHub App token to post commit statuses and read PR and team info
- [x] Change the `PullRequest` class to use the GitHub App client instead of the OAuth client
- [x] Control user access to repositories based on which installations the user has access to on GitHub ([API docs](https://developer.github.com/v3/apps/installations/#list-repositories-accessible-to-the-user-for-an-installation))

**Comment by aergonaut** [comment]
No longer going to track installations since I don't think I need that data for Cody's current plans. It seems to be more useful if I needed to limit accounts to a certain number of repos or something like that.

**Comment by aergonaut** [comment]
This is all done.
