### ISSUE TITLE
Use VCR in tests

### ISSUE THREAD

**Issue by aergonaut** [aergonaut/cody#70]
We're making more external requests and that's making setting up all the mocks necessary for every test more painful.

I did not use VCR initially because what I wanted to simulate was incoming HTTP requests. But now that we make more requests to GitHub for PR info, using VCR to mock those requests makes more sense.

## TODO

- [ ] Setup test organization and test repo
- [ ] Setup test credentials for recording cassettes
- [ ] Install VCR
- [ ] Remove Webmock
- [ ] Record all the cassettes (use JSON cassette format)
