### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by aergonaut** [aergonaut/cody#75]
Track analytics somehow

## TODO

- [ ] Choose an analytics repository. Should support StatsD.
- [ ] Choose metrics to monitor.

## Metrics

- [ ] Use of `cody replace` on each Rule. Who issued the command, who was replaced, who is the new reviewer
- [ ] Cycle time per reviewer
- [ ] "Time to first review"
- [ ] "Time to approved"
