### ISSUE TITLE
December 2021 deprecations

### ISSUE THREAD

**Issue by aergonaut** [aergonaut/cody#873]
This is a tracking issue for Cody features that will be deprecated starting December 2021, for eventual removal in January 2022.

- [x] `ignore_labels` setting - No replacement. Use Draft PRs instead. #923 
- [x] `minimum_reviewers_required` setting - No replacement. Use GitHub's native setting instead. #923 
- [x] Cody Slack app - Use GitHub's Slack Reminders app instead. #933
- [x] Daily digest email #931

**Comment by aergonaut** [comment]
#923 will remove transit-ruby, thereby removing repository settings, as it is the main blocker to upgrading to Ruby 3.

**Comment by aergonaut** [comment]
All deprecated features have been removed.
